name: Check git dependencies

on:
  push:

jobs:
  doc-only-changes:
    runs-on: ubuntu-latest

    outputs:
        should_skip: ${{ steps.skip_check.outputs.should_skip }}

    steps:
    - name: Check if only documentation changes
      id: skip_check
      uses: fkirc/skip-duplicate-actions@v5
      with:
        paths_ignore: '["**/*.md", "**/*.rst", "**/LICENSE", "**/NOTICE"]'

  build:
    if: needs.doc-only-changes.outputs.should_skip != 'true'
    runs-on: ubuntu-latest

    defaults:
      run:
        shell: bash

    steps:

    - uses: actions/checkout@v2

    - name: Check git dependencies
      run: |
        .github/bin/check-git-dependencies
