name: Check HLint

on:
  push:
  merge_group:

# Limit concurrent runs of this workflow within a single PR
concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest

    defaults:
      run:
        shell: bash

    steps:

    - uses: actions/checkout@v2

    - name: Install dependencies
      run: |
        sudo apt-get -y install libtinfo5

    - name: 'Set up HLint'
      uses: rwe/actions-hlint-setup@v1
      with:
        version: 3.3

    - name: 'Run HLint'
      uses: rwe/actions-hlint-run@v2
